[project]
name = "TMAs"
version = "0.1.0"
description = "Module for segmenting pathological images of tissue microarrays"
dependencies = [
    "torch",
    "numpy",
    "huggingface_hub",
    "opencv-python",
]
authors = [
    { name="BOSCH Valentin", email="val.bosch2001@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.8"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"