[project]
name = "mon-module"
version = "0.1.0"
description = "Mon premier module PyPI"
authors = [
    { name="BOSCH Valentin", email="val.bosch2001@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.8"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"